### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/BambuLabsListener#3]
I tested this on another Windows machine on my network and got this issue:
```
Unhandled exception. MQTTnet.Exceptions.MqttCommunicationTimedOutException: The operation has timed out.
   at MQTTnet.Implementations.CrossPlatformSocket.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectInternal(IMqttChannelAdapter channelAdapter, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(MqttClientOptions options, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\derek\source\repos\BambuLabsListener\Program.cs:line 25
   at Program.<Main>(String[] args)
```

**Comment by derekantrican** [comment]
Installing MQTT Explorer, connecting through that, then trying to `dotnet run` this program seemed to work. Not sure if that sets up some configs or anything
